import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const languages = {
  en: { code: 'en', name: 'English', flag: '🇬🇧' },
  ms: { code: 'ms', name: 'Bahasa Malaysia', flag: '🇲🇾' },
  zh: { code: 'zh', name: '中文', flag: '🇨🇳' },
  ta: { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' }
};

const translations = {
  en: {
    hero_title: 'Together, We Find the Way',
    hero_description: 'Access services, find support, and stay connected with your community.',
    hero_image_alt: 'Community Together',
    government_services: 'Government Services',
    government_services_desc: 'Access essential government services and information',
    healthcare: 'Healthcare Resources',
    healthcare_desc: 'Find healthcare facilities and medical information',
    community: 'Community & Social Support',
    community_desc: 'Connect with community resources and support groups',
    employment: 'Employment & Income Support',
    employment_desc: 'Access job opportunities and career resources',
    digital: 'Digital Literacy',
    digital_desc: 'Learn digital skills and online safety',
    contact: 'Contact Us',
    welcome: 'Welcome to KitaCare',
    hero_subtitle: 'Empowering Malaysian seniors and low-income families with easy access to vital services.',
    about_title: 'How KitaCare Helps You',
    how_it_helps: 'Made simple, accessible, and useful for everyone',
    easy_access: 'Easy Access',
    easy_access_desc: 'Simple interface designed for users with varying digital literacy.',
    multilingual: 'Multilingual Support',
    multilingual_desc: 'Content available in multiple languages for better accessibility.',
    mobile_friendly: 'Mobile Friendly',
    mobile_friendly_desc: 'Access services from any device, anytime, anywhere.',
    get_started: 'Get Started',
    learn_more: 'Learn More',
    contact_us: 'Contact Us',
    footer_description: 'Empowering Malaysian seniors and low-income families with easy access to vital services.',
    address: 'KitaCare Malaysia',
    email: 'Email',
    phone: 'Phone',
    rights_reserved: 'All rights reserved.',
    benefit1: ' Centralized & Simple Access',
    benefit1_desc: 'All essential services—government help, healthcare info, community support—are in one place.No more jumping between apps or searching confusing websites.',
    benefit2: 'Saves Time & Money',
    benefit2_desc: 'Learn how to book clinic appointments, apply for aid, or get transport help without traveling to multiple offices.',
    benefit3: 'Learn Digital Skills Easily',
    benefit3_desc: 'Bite-sized lessons for beginners on how to use smartphones, avoid scams, send messages, and more.Helps people feel more confident and independent with technology.',
    get_directions: 'Get Directions',
    gov_services_intro: 'Access government resources, applications, and official documents through these essential services.',
    available_now: 'Available Now',
    coming_soon: 'Coming Soon',
    services_offered: 'Services Offered:',
    access_service: 'Access Service',
    online_applications: 'Online Applications',
    status_checking: 'Status Checking',
    document_downloads: 'Document Downloads',
    info_portal: 'Information Portal',
    about_title: 'How KitaCare Helps You',
    how_it_helps: 'Made simple, accessible, and useful for everyone',
    resources: 'Why KitaCare?',
    resources_desc:'KitaCare provides a wide range of essential services to help you get through your day-to-day life.',
    question3: 'How do I access government services?',
    answer3: 'You can access government services through our platform by navigating to the Government Services section.',
    question2: 'Is KitaCare free to use?',
    answer2: 'Yes, KitaCare is completely free for all users.',
    question1: 'What is KitaCare?',
    answer1: 'KitaCare is a platform designed to empower Malaysian seniors and low-income families by providing easy access to essential services.',
    gov_services_desc: 'Access government resources',
    healthcare_title: 'Healthcare Resources',
    healthcare_intro: 'Find healthcare facilities and access medical information easily.',
    find_facility: 'Find Facility',
    find : 'Find',
    Any : 'Any',
    emergency: 'Emergency',
    appointment: 'Book Appointment',
    medical_records: 'Medical Records',
    faq: 'Frequently Asked Questions',
    community_title: 'Community & Social Support',
    community_intro: 'Connect with your local community and find support services.',
    join_community: 'Join Community',
    find_support: 'Find Support',
    volunteer: 'Volunteer',
    events: 'Community Events',
    contacts: 'Social Workers Contacts',
    contacts_desc: 'Contact social workers for support and assistance.',
    support_desc: 'Support Services Directory',
    employment_title: 'Employment & Income Support',
    employment_intro: 'Find job opportunities and access career resources.',
    search_jobs: 'Search',
    career_resources: 'Career Resources',
    training: 'Training Programs',
    financial_aid: 'Financial Aid',
    peer_support: 'Peer Support & Discussion Forums',
    peer_desc: 'Share experiences, ask questions, and get emotional support.',
    help : 'Ask & Offer for Help',
    help_desc : 'Ask for help or offer assistance to others.',
    digital_title: 'Digital Literacy',
    digital_intro: 'Learn essential digital skills and stay safe online.',
    basic_skills: 'Basic Skills',
    online_safety: 'Online Safety',
    digital_tools: 'Digital Tools',
    practice_exercises: 'Practice Exercises',
    AI: 'AI Learning',
    AI_desc: 'Learn about AI and its applications',
    Smartphone_usage: 'Smartphone Usage',
    smartphone_desc: 'Learn how to use smartphones and apps',
    online_services: 'Online Services',
    online_desc: 'Learn about online services and how to use them',
    online_payment: 'Online Payment',
    payment_desc: 'Learn about online payment and how to use it',
    safety_desc: 'Learn about online safety and how to stay safe online',
    safety: 'Safety',
    oku: 'Accessibility Tools for OKU',
    oku_desc: 'Learn about screen readers, voice commands, and mobile settings for people with disabilities.',
    accessibility: 'Accessibility',
    maps: 'Maps usage',
    maps_desc: 'Learn to find places, get directions, and use real-time travel info.',
    scam: 'Scam Awareness',
    scam_desc: 'Learn to recognize and avoid scams',
    our_services: 'Our Services',
    our_services_desc: 'We offer a wide range of services to help you get through your day-to-day life.',
    quick_links: 'Quick Links',

    not_found: 'Page Not Found',
    not_found_message: 'The page you are looking for does not exist.',
    back_home: 'Back to Home',
    ai_learning: 'AI Learning',
    ai_learning_desc: 'Learn about artificial intelligence and its applications in daily life',
    ai_intro_title: 'Introduction to AI',
    ai_intro_content: 'Artificial Intelligence (AI) is technology that enables computers to learn, reason, and make decisions like humans. It\'s already part of our daily lives through smartphones, smart home devices, and online services. In this journey, you\'ll learn how AI works and how to use it safely and effectively.',
    ai_basics_title: 'Understanding AI Basics',
    ai_basics_content: 'AI systems can recognize speech, understand text, and make predictions. They learn from examples and improve over time. Common AI applications include voice assistants, translation tools, and recommendation systems. Understanding these basics helps you make better use of AI tools.',
    ai_applications_title: 'AI in Daily Life',
    ai_applications_content: 'AI helps with everyday tasks like setting reminders, finding information, and managing schedules. It can assist with language translation, image recognition, and even healthcare monitoring. Learn how to use these features to make your life easier and more efficient.',
    ai_ethics_title: 'AI Safety and Ethics',
    ai_ethics_content: 'While AI is powerful, it\'s important to use it safely and ethically. Be aware of privacy concerns, verify information from AI sources, and understand the limitations of AI systems. This knowledge helps you make informed decisions when using AI tools.',
    ai_future_title: 'The Future of AI',
    ai_future_content: 'AI technology is constantly evolving, bringing new opportunities and challenges. Stay informed about developments in AI to make the most of these tools. Remember that AI is a tool to assist you, not replace human judgment and creativity.',
    step: 'Step',
    next: 'Next',
    finish: 'Finish',
    completed: 'Completed',

    connect: 'Connect',
    apply_now: 'Apply Now',
    hot_job: 'High Demand',
    footer: 'Empowering Malaysian seniors and low-income families with easy access to vital services.',
    ideas: 'Connecting Ideas, Empowering Innovation',
    // Careers page translations
    careers: 'Careers',
    careers_intro: 'Explore exciting career opportunities and find your next professional journey.',
    requirements: 'Requirements',
    salary_range: 'Salary Range',
    location: 'Location',
    company: 'Company',
    job_type: 'Job Type',
    experience_level: 'Experience Level',
    full_time: 'Full-time',
    part_time: 'Part-time',
    contract: 'Contract',
    entry_level: 'Entry Level',
    mid_level: 'Mid Level',
    senior: 'Senior',
    application_success: 'Application submitted successfully!',
    application_error: 'Failed to submit application. Please try again.',
    retry: 'Retry',

    // Community Support page translations
    community_support: 'Community Support',
    community_support_intro: 'Access community resources and support services to help you thrive.',
    senior_citizen_support: 'Senior Citizen Support',
    senior_citizen_support_desc: 'Comprehensive support services for senior citizens including healthcare, social activities, and assistance programs.',
    community_centers: 'Community Centers',
    community_centers_desc: 'Local community centers offering various programs and activities for all age groups.',
    volunteer_programs: 'Volunteer Programs',
    volunteer_programs_desc: 'Join our volunteer programs and make a difference in your community.',
    emergency_support: 'Emergency Support',
    emergency_support_desc: '24/7 emergency support services for immediate assistance and crisis intervention.',
    family_support: 'Family Support',
    family_support_desc: 'Comprehensive family support services including parenting resources and family activities.',
    mental_health: 'Mental Health Services',
    mental_health_desc: 'Professional mental health support and wellness programs.',
    services_offered: 'Services Offered',
  },
  ms: {
    "hero_title": "Bersama, Kita Temui Jalan",
    "hero_description": "Akses perkhidmatan, cari sokongan, dan kekal berhubung dengan komuniti anda.",
    "hero_image_alt": "Komuniti Bersama",
    "government_services": "Perkhidmatan Kerajaan",
    "government_services_desc": "Akses perkhidmatan kerajaan yang penting dan maklumat",
    "healthcare": "Sumber Kesihatan",
    "healthcare_desc": "Cari kemudahan kesihatan dan maklumat perubatan",
    "community": "Sokongan Komuniti & Sosial",
    "community_desc": "Hubungkan dengan sumber komuniti dan kumpulan sokongan",
    "employment": "Sokongan Pekerjaan & Pendapatan",
    "employment_desc": "Akses peluang pekerjaan dan sumber kerjaya",
    "digital": "Literasi Digital",
    "digital_desc": "Pelajari kemahiran digital dan keselamatan dalam talian",
    "contact": "Hubungi Kami",
    "welcome": "Selamat Datang ke KitaCare",
    "hero_subtitle": "Memperkasakan warga emas dan keluarga berpendapatan rendah Malaysia dengan akses mudah kepada perkhidmatan penting.",
    "about_title": "Bagaimana KitaCare Membantu Anda",
    "how_it_helps": "Dibuat ringkas, mudah diakses, dan berguna untuk semua",
    "easy_access": "Akses Mudah",
    "easy_access_desc": "Antara muka mudah yang direka untuk pengguna dengan tahap celik digital yang berbeza.",
    "multilingual": "Sokongan Pelbagai Bahasa",
    "multilingual_desc": "Kandungan tersedia dalam pelbagai bahasa untuk kebolehcapaian yang lebih baik.",
    "mobile_friendly": "Mesra Mudah Alih",
    "mobile_friendly_desc": "Akses perkhidmatan dari mana-mana peranti, bila-bila masa, di mana sahaja.",
    "get_started": "Mulakan",
    "learn_more": "Ketahui Lebih Lanjut",
    "contact_us": "Hubungi Kami",
    "footer_description": "Memperkasakan warga emas dan keluarga berpendapatan rendah Malaysia dengan akses mudah kepada perkhidmatan penting.",
    "address": "KitaCare Malaysia",
    "email": "Emel",

    find : 'Cari',
    Any : 'Semua',
    
    quick_links: 'Pautan Pantas',
    "phone": "Telefon",
    "rights_reserved": "Hak cipta terpelihara.",
    "benefit1": "Akses Pusat & Mudah",
    "benefit1_desc": "Semua perkhidmatan penting—bantuan kerajaan, maklumat kesihatan, sokongan komuniti—dalam satu tempat. Tidak perlu lagi lompat antara aplikasi atau mencari laman web yang mengelirukan.",
    "benefit2": "Menjimatkan Masa & Wang",
    "benefit2_desc": "Pelajari bagaimana menempah janji temu klinik, memohon bantuan, atau mendapatkan bantuan pengangkutan tanpa perlu pergi ke pelbagai pejabat.",
    "benefit3": "Pelajari Kemahiran Digital Dengan Mudah",
    "benefit3_desc": "Pelajaran kecil untuk pemula tentang cara menggunakan telefon pintar, mengelakkan penipuan, menghantar mesej, dan banyak lagi. Membantu orang merasa lebih yakin dan berdikari dengan teknologi.",
    "get_directions": "Dapatkan Arah",
    "gov_services_intro": "Akses sumber kerajaan, permohonan, dan dokumen rasmi melalui perkhidmatan penting ini.",
    "available_now": "Tersedia Sekarang",
    "coming_soon": "Akan Datang",
    "services_offered": "Perkhidmatan Yang Ditawarkan:",
    "access_service": "Akses Perkhidmatan",
    "online_applications": "Permohonan Dalam Talian",
    "status_checking": "Semakan Status",
    "document_downloads": "Muat Turun Dokumen",
    "info_portal": "Portal Maklumat",
    "about_title": "Bagaimana KitaCare Membantu Anda",
    "how_it_helps": "Dibuat ringkas, mudah diakses, dan berguna untuk semua",
    "resources": "Mengapa KitaCare?",
    "resources_desc": "KitaCare menyediakan pelbagai perkhidmatan penting untuk membantu anda menjalani kehidupan seharian.",
    "question3": "Bagaimana saya mengakses perkhidmatan kerajaan?",
    "answer3": "Anda boleh mengakses perkhidmatan kerajaan melalui platform kami dengan menavigasi ke bahagian Perkhidmatan Kerajaan.",
    "question2": "Adakah KitaCare percuma untuk digunakan?",
    "answer2": "Ya, KitaCare adalah percuma sepenuhnya untuk semua pengguna.",
    "question1": "Apakah KitaCare?",
    "answer1": "KitaCare adalah platform yang direka untuk memberdayakan warga emas Malaysia dan keluarga berpendapatan rendah dengan menyediakan akses mudah kepada perkhidmatan penting.",
    "gov_services_desc": "Akses sumber kerajaan",
    "healthcare_title": "Sumber Kesihatan",
    "healthcare_intro": "Cari kemudahan kesihatan dan akses maklumat perubatan dengan mudah.",
    "find_facility": "Cari Kemudahan",
    "emergency": "Kecemasan",
    "appointment": "Tempah Janji Temu",
    "medical_records": "Rekod Perubatan",
    "faq": "Soalan Lazim",
    "community_title": "Sokongan Komuniti & Sosial",
    "community_intro": "Hubungkan dengan komuniti tempatan anda dan cari perkhidmatan sokongan.",
    "join_community": "Sertai Komuniti",
    "find_support": "Cari Sokongan",
    "volunteer": "Berkhidmat Sebagai Sukarelawan",
    "events": "Acara Komuniti",
    "contacts": "Kontak Pekerja Sosial",
    "contacts_desc": "Hubungi pekerja sosial untuk sokongan dan bantuan.",
    "support_desc": "Direktori Perkhidmatan Sokongan",
    "employment_title": "Sokongan Pekerjaan & Pendapatan",
    "employment_intro": "Cari peluang pekerjaan dan akses sumber kerjaya.",
    "search_jobs": "Carian",
    "career_resources": "Sumber Kerjaya",
    "training": "Program Latihan",
    "financial_aid": "Bantuan Kewangan",
    "peer_support": "Sokongan Rakan Sebaya & Forum Perbincangan",
    "peer_desc": "Kongsi pengalaman, ajukan soalan, dan dapatkan sokongan emosi.",
    "help": "Tanya & Tawarkan Bantuan",
    "help_desc": "Minta bantuan atau tawarkan bantuan kepada orang lain.",
    "digital_title": "Literasi Digital",
    "digital_intro": "Pelajari kemahiran digital yang penting dan kekal selamat dalam talian.",
    "basic_skills": "Kemahiran Asas",
    "online_safety": "Keselamatan Dalam Talian",
    "digital_tools": "Alat Digital",
    "practice_exercises": "Latihan Praktikal",
    "AI": "Pembelajaran AI",
    "AI_desc": "Pelajari tentang AI dan aplikasinya",
    "Smartphone_usage": "Penggunaan Telefon Pintar",
    "smartphone_desc": "Pelajari cara menggunakan telefon pintar dan aplikasi",
    "online_services": "Perkhidmatan Dalam Talian",
    "online_desc": "Pelajari tentang perkhidmatan dalam talian dan cara menggunakannya",
    "online_payment": "Pembayaran Dalam Talian",
    "payment_desc": "Pelajari tentang pembayaran dalam talian dan cara menggunakannya",
    "safety_desc": "Pelajari tentang keselamatan dalam talian dan cara kekal selamat dalam talian",
    "safety": "Keselamatan",
    "oku": "Alat Kebolehcapaian untuk OKU",
    "oku_desc": "Pelajari tentang pembaca skrin, arahan suara, dan tetapan mudah alih untuk orang kurang upaya.",
    "accessibility": "Kebolehcapaian",
    "maps": "Penggunaan Peta",
    "maps_desc": "Pelajari cara mencari tempat, mendapatkan arah, dan menggunakan maklumat perjalanan masa nyata.",
    "scam": "Kesedaran Penipuan",
    "scam_desc": "Pelajari cara mengenali dan mengelakkan penipuan",
    "our_services": "Perkhidmatan Kami",
    "our_services_desc": "Kami menawarkan pelbagai perkhidmatan untuk membantu anda menjalani kehidupan seharian.",
    "not_found": "Halaman Tidak Dijumpai",
    "not_found_message": "Halaman yang anda cari tidak wujud.",
    "back_home": "Kembali ke Laman Utama",
    "ai_learning": "Pembelajaran AI",
    "ai_learning_desc": "Pelajari tentang kecerdasan buatan dan aplikasinya dalam kehidupan seharian",
    "ai_intro_title": "Pengenalan kepada AI",
    "ai_intro_content": "Kecerdasan Buatan (AI) adalah teknologi yang membolehkan komputer belajar, berfikir, dan membuat keputusan seperti manusia. Ia sudah menjadi sebahagian daripada kehidupan harian kita melalui telefon pintar, peranti rumah pintar, dan perkhidmatan dalam talian. Dalam perjalanan ini, anda akan belajar bagaimana AI berfungsi dan bagaimana menggunakannya dengan selamat dan berkesan.",
    "ai_basics_title": "Memahami Asas AI",
    "ai_basics_content": "Sistem AI boleh mengenal suara, memahami teks, dan membuat ramalan. Mereka belajar dari contoh dan bertambah baik dari masa ke masa. Aplikasi AI biasa termasuk pembantu suara, alat terjemahan, dan sistem cadangan. Memahami asas-asas ini membantu anda menggunakan alat AI dengan lebih baik.",
    "ai_applications_title": "AI dalam Kehidupan Seharian",
    "ai_applications_content": "AI membantu dalam tugas harian seperti menetapkan peringatan, mencari maklumat, dan menguruskan jadual. Ia boleh membantu dengan terjemahan bahasa, pengecaman imej, dan pemantauan kesihatan. Pelajari cara menggunakan ciri-ciri ini untuk memudahkan hidup anda dan lebih cekap.",
    "ai_ethics_title": "Keselamatan dan Etika AI",
    "ai_ethics_content": "Walaupun AI berkuasa, adalah penting untuk menggunakannya dengan selamat dan beretika. Berhati-hati dengan kebimbangan privasi, sahkan maklumat dari sumber AI, dan fahami had-had sistem AI. Pengetahuan ini membantu anda membuat keputusan yang bijak semasa menggunakan alat AI.",
    "ai_future_title": "Masa Depan AI",
    "ai_future_content": "Teknologi AI sentiasa berkembang, membawa peluang dan cabaran baru. Kekal maklum tentang perkembangan AI untuk memanfaatkan alat ini. Ingatlah bahawa AI adalah alat untuk membantu anda, bukan menggantikan penilaian dan kreativiti manusia.",
    "step": "Langkah",
    "next": "Seterusnya",
    "finish": "Siap",
    "completed": "Selesai",

    // Careers page translations
    careers: 'Kerjaya',
    careers_intro: 'Terokai peluang kerjaya yang menarik dan temui perjalanan profesional seterusnya anda.',
    requirements: 'Keperluan',
    salary_range: 'Julat Gaji',
    location: 'Lokasi',
    apply_now: 'Mohon Sekarang',
    hot_job: 'Permintaan Tinggi',
    company: 'Syarikat',
    job_type: 'Jenis Pekerjaan',
    experience_level: 'Tahap Pengalaman',
    full_time: 'Sepenuh Masa',
    part_time: 'Separuh Masa',
    contract: 'Kontrak',
    entry_level: 'Tahap Permulaan',
    mid_level: 'Tahap Pertengahan',
    senior: 'Senior',
    application_success: 'Permohonan berjaya dihantar!',
    application_error: 'Gagal menghantar permohonan. Sila cuba lagi.',
    retry: 'Cuba Lagi',

    connect: 'Hubungi',
apply_now: 'Mohon Sekarang',
hot_job: 'Permintaan Tinggi',
footer: 'Memperkasakan warga emas Malaysia dan keluarga berpendapatan rendah dengan akses mudah kepada perkhidmatan penting.',
ideas: 'Menghubungkan Idea, Memperkasakan Inovasi',

    // Community Support page translations
    community_support: 'Sokongan Komuniti',
    community_support_intro: 'Akses sumber komuniti dan perkhidmatan sokongan untuk membantu anda berkembang.',
    senior_citizen_support: 'Sokongan Warga Emas',
    senior_citizen_support_desc: 'Perkhidmatan sokongan komprehensif untuk warga emas termasuk penjagaan kesihatan, aktiviti sosial, dan program bantuan.',
    community_centers: 'Pusat Komuniti',
    community_centers_desc: 'Pusat komuniti tempatan yang menawarkan pelbagai program dan aktiviti untuk semua peringkat umur.',
    volunteer_programs: 'Program Sukarelawan',
    volunteer_programs_desc: 'Sertai program sukarelawan kami dan buat perbezaan dalam komuniti anda.',
    emergency_support: 'Sokongan Kecemasan',
    emergency_support_desc: 'Perkhidmatan sokongan kecemasan 24/7 untuk bantuan segera dan intervensi krisis.',
    family_support: 'Sokongan Keluarga',
    family_support_desc: 'Perkhidmatan sokongan keluarga komprehensif termasuk sumber keibubapaan dan aktiviti keluarga.',
    mental_health: 'Perkhidmatan Kesihatan Mental',
    mental_health_desc: 'Sokongan kesihatan mental profesional dan program kesejahteraan.',
    connect: 'Hubungkan',
    services_offered: 'Perkhidmatan Yang Ditawarkan',
  },
  zh: {
    "hero_title": "携手同行，共创未来",
    "hero_description": "获取服务，寻找支持，与社区保持联系。",
    "hero_image_alt": "社区团结在一起",
    "government_services": "政府服务",
    "government_services_desc": "获取重要的政府服务和信息",
    "healthcare": "医疗资源",
    "healthcare_desc": "查找医疗机构和健康信息",
    "community": "社区与社会支持",
    "community_desc": "连接社区资源和支持团体",
    "employment": "就业与收入支持",
    "employment_desc": "获取工作机会和职业资源",
    "digital": "数字素养",
    "digital_desc": "学习数字技能与网络安全",
    "contact": "联系我们",
    "welcome": "欢迎来到 KitaCare",
    "hero_subtitle": "为马来西亚的长者和低收入家庭提供便捷的重要服务访问渠道。",
    "about_title": "KitaCare 如何帮助您",
    "how_it_helps": "简单、易用、适合所有人",
    "easy_access": "轻松访问",
    "easy_access_desc": "界面简洁，适合不同数字素养水平的用户。",
    "multilingual": "多语言支持",
    "multilingual_desc": "内容提供多种语言版本，提升可访问性。",
    "mobile_friendly": "移动设备友好",
    "mobile_friendly_desc": "随时随地，从任意设备访问服务。",
    quick_links: '快速链接',
    "get_started": "立即开始",
    "learn_more": "了解更多",
    "contact_us": "联系我们",
    "footer_description": "为马来西亚的长者和低收入家庭提供便捷的重要服务访问渠道。",
    "address": "KitaCare 马来西亚",
    "email": "电子邮件",
    "phone": "电话",
    "rights_reserved": "版权所有。",
    "benefit1": "集中 & 简便的访问",
    "benefit1_desc": "所有重要服务——政府援助、健康信息、社区支持——尽在一站式平台。无需再跳转应用或浏览复杂网站。",
    "benefit2": "节省时间与金钱",
    "benefit2_desc": "学习如何预约诊所、申请援助或获取交通支持，无需亲临多个办公室。",
    "benefit3": "轻松学习数字技能",
    "benefit3_desc": "为初学者提供简短课程，包括如何使用智能手机、防诈骗、发消息等内容，增强对科技的信心和独立性。",
    "get_directions": "获取路线",
    "gov_services_intro": "通过这些基础服务访问政府资源、申请和官方文件。",
    "available_now": "现已开放",
    "coming_soon": "即将推出",
    "services_offered": "提供的服务：",
    "access_service": "访问服务",
    "online_applications": "在线申请",
    "status_checking": "状态查询",
    "document_downloads": "文件下载",
    "info_portal": "信息门户",
    "resources": "为什么选择 KitaCare？",
    "resources_desc": "KitaCare 提供多种基本服务，帮助您应对日常生活。",
    "question3": "我如何访问政府服务？",
    "answer3": "您可以通过我们的平台，进入政府服务部分来获取相关服务。",
    "question2": "KitaCare 是免费的吗？",
    "answer2": "是的，KitaCare 对所有用户完全免费。",
    "Any": "任何",
    find : '搜索',
    "question1": "什么是 KitaCare？",
    "answer1": "KitaCare 是一个帮助马来西亚长者和低收入家庭便捷获取关键服务的平台。",
    "gov_services_desc": "获取政府资源",
    "healthcare_title": "医疗资源",
    "healthcare_intro": "轻松查找医疗设施并获取医学信息。",
    "find_facility": "查找设施",
    "emergency": "紧急情况",
    "appointment": "预约",
    "medical_records": "医疗记录",
    "faq": "常见问题",
    "community_title": "社区与社会支持",
    "community_intro": "与当地社区建立联系，寻找支持服务。",
    "join_community": "加入社区",
    "find_support": "寻找支持",
    "volunteer": "志愿服务",
    "events": "社区活动",
    "contacts": "社会工作者联系方式",
    "contacts_desc": "联系社会工作者以获取支持与帮助。",
    "support_desc": "支持服务目录",
    "employment_title": "就业与收入支持",
    "employment_intro": "查找工作机会并获取职业资源。",
    "search_jobs": "搜索",
    "career_resources": "职业资源",
    "training": "培训计划",
    "financial_aid": "经济援助",
    "peer_support": "同伴支持与讨论区",
    "peer_desc": "分享经验，提出问题，获得情感支持。",
    "help": "请求与提供帮助",
    "help_desc": "请求帮助或为他人提供协助。",
    "digital_title": "数字素养",
    "digital_intro": "学习基础数字技能并安全上网。",
    "basic_skills": "基础技能",
    "online_safety": "网络安全",
    "digital_tools": "数字工具",
    "practice_exercises": "实践练习",
    "AI": "人工智能学习",
    "AI_desc": "了解人工智能及其应用",
    "Smartphone_usage": "智能手机使用",
    "smartphone_desc": "学习如何使用智能手机与应用程序",
    "online_services": "在线服务",
    "online_desc": "了解在线服务及其使用方法",
    "online_payment": "在线支付",
    "payment_desc": "学习如何使用在线支付服务",
    "safety_desc": "了解网络安全及如何保护自己",
    "safety": "安全",
    "oku": "残障人士辅助工具",
    "oku_desc": "了解屏幕阅读器、语音指令和手机设置等辅助功能。",
    "accessibility": "可访问性",
    "maps": "地图使用",
    "maps_desc": "学习查找地点、获取路线、使用实时出行信息。",
    "scam": "防骗知识",
    "scam_desc": "学习识别和避免网络诈骗",
    "our_services": "我们的服务",
    "our_services_desc": "我们提供多种服务，助您应对日常生活。",
    "not_found": "页面未找到",
    "not_found_message": "您要找的页面不存在。",
    "back_home": "返回首页",
    "ai_learning": "人工智能学习",
    "ai_learning_desc": "了解人工智能及其在日常生活中的应用",
    "ai_intro_title": "人工智能简介",
    "ai_intro_content": "人工智能（AI）是一种让计算机像人一样学习、思考和决策的技术。它已经通过智能手机、智能家居设备和在线服务进入我们的日常生活。在这个学习过程中，您将了解 AI 的工作原理，并学会如何安全有效地使用它。",
    "ai_basics_title": "了解 AI 基础",
    "ai_basics_content": "AI 系统能够识别语音、理解文本并做出预测。它们通过学习示例不断进步。常见的 AI 应用包括语音助手、翻译工具和推荐系统。掌握这些基础知识有助于您更好地使用 AI 工具。",
    "ai_applications_title": "AI 在日常生活中的应用",
    "ai_applications_content": "AI 能协助完成日常任务，如设置提醒、查找信息和安排时间表。它还可进行语言翻译、图像识别甚至健康监测。学习如何使用这些功能，让生活更轻松、更高效。",
    "ai_ethics_title": "AI 的安全与伦理",
    "ai_ethics_content": "虽然 AI 功能强大，但安全和道德使用至关重要。注意隐私问题，核实 AI 信息来源，并了解其局限性。掌握这些知识能帮助您做出明智的决策。",
    "ai_future_title": "AI 的未来",
    "ai_future_content": "AI 技术持续发展，带来新的机遇和挑战。关注 AI 动态，充分利用这些工具。记住：AI 是辅助工具，不能取代人类的判断与创造力。",
    "step": "步骤",
    "next": "下一步",
    "finish": "完成",
    "completed": "已完成",

    // Careers page translations
    careers: '职业',
careers_intro: '探索令人兴奋的职业机会，找到您的下一段职业旅程。',
requirements: '要求',
salary_range: '薪资范围',
location: '地点',
apply_now: '立即申请',
hot_job: '高需求',
company: '公司',
job_type: '工作类型',
experience_level: '经验水平',
full_time: '全职',
part_time: '兼职',
contract: '合同工',
entry_level: '入门级',
mid_level: '中级',
senior: '高级',
application_success: '申请提交成功！',
application_error: '申请提交失败。请重试。',
retry: '重试',
connect: '联系',
apply_now: '立即申请',
hot_job: '高需求',
footer: '为马来西亚老年人和低收入家庭提供便捷获取重要服务的途径。',
ideas: '连接创意，赋能创新',

// Community Support page translations
community_support: '社区支持',
community_support_intro: '获取社区资源和支持服务，帮助您蓬勃发展。',
senior_citizen_support: '老年人支持',
senior_citizen_support_desc: '为老年人提供全面的支持服务，包括医疗保健、社交活动和援助计划。',
community_centers: '社区中心',
community_centers_desc: '当地社区中心为各年龄段提供各种项目和活动。',
volunteer_programs: '志愿者计划',
volunteer_programs_desc: '加入我们的志愿者计划，为您的社区做出改变。',
emergency_support: '紧急支持',
emergency_support_desc: '全天候紧急支持服务，提供即时援助和危机干预。',
family_support: '家庭支持',
family_support_desc: '全面的家庭支持服务，包括育儿资源和家庭活动。',
mental_health: '心理健康服务',
mental_health_desc: '专业心理健康支持和健康计划。',
connect: '联系',
services_offered: '提供的服务',
  },
  ta: {
    "hero_title": "ஒன்றாகவே நம்மால் முடியும்",
    "hero_description": "சேவைகளை அணுகவும், உதவிகளை பெறவும், உங்கள் சமூகத்துடன் இணைந்திருக்கவும்.",
    "hero_image_alt": "சமூக ஒருங்கிணைப்பு",
    "government_services": "அரசு சேவைகள்",
    "government_services_desc": "முக்கியமான அரசு சேவைகள் மற்றும் தகவல்களை அணுகவும்",
    "healthcare": "மருத்துவ வளங்கள்",
    "healthcare_desc": "மருத்துவ மையங்களை மற்றும் தகவல்களை கண்டறியவும்",
    "community": "சமூக மற்றும் சமூக ஆதரவு",
    "community_desc": "சமூக ஆதாரங்கள் மற்றும் ஆதரவு குழுக்களுடன் இணைக்கவும்",
    "employment": "வேலை மற்றும் வருமான ஆதரவு",
    "employment_desc": "வேலை வாய்ப்புகள் மற்றும் தொழில் வளங்களை அணுகவும்",
    "digital": "டிஜிட்டல் கல்வி",
    "digital_desc": "டிஜிட்டல் திறன்கள் மற்றும் ஆன்லைன் பாதுகாப்பை கற்றுக்கொள்ளுங்கள்",
    "contact": "எங்களை தொடர்புகொள்ள",
    "welcome": "கிட்டாகேர் இற்கு வரவேற்கிறோம்",
    "hero_subtitle": "மலேசிய மூதாட்டிகள் மற்றும் குறைந்த வருமான குடும்பங்களுக்கு முக்கியமான சேவைகளை எளிதாக அணுக வலுவூட்டுதல்.",
    "about_title": "கிட்டாகேர் உங்களை எவ்வாறு உதவுகிறது",
    "how_it_helps": "எளிமையானது, அணுகக்கூடியது மற்றும் அனைவருக்கும் பயனுள்ளதாக உள்ளது",
    "easy_access": "எளிதான அணுகல்",
    "easy_access_desc": "விவித டிஜிட்டல் திறன் உள்ளவர்களுக்காக வடிவமைக்கப்பட்ட எளிய இடைமுகம்.",
    "multilingual": "பல மொழி ஆதரவு",
    "multilingual_desc": "மேம்பட்ட அணுகலுக்காக பல மொழிகளில் உள்ளடக்கம்.",
    "mobile_friendly": "மொபைல் நட்பு",
    "mobile_friendly_desc": "எந்த சாதனத்திலிருந்தும், எப்போதும், எங்கு வேண்டுமானாலும் சேவைகளை அணுகுங்கள்.",
    "get_started": "தொடங்குங்கள்",
    "learn_more": "மேலும் அறிக",
    "contact_us": "எங்களை தொடர்புகொள்ளுங்கள்",
    connect: 'இணைக்க',
apply_now: 'இப்போது விண்ணப்பிக்கவும்',
hot_job: 'அதிக தேவை',
footer: 'மலேசிய மூத்த குடிமக்கள் மற்றும் குறைந்த வருமானம் உள்ள குடும்பங்களுக்கு அத்தியாவசிய சேவைகளை எளிதாக அணுகுவதற்கு அதிகாரமளித்தல்.',
ideas: 'கருத்துக்களை இணைத்தல், புதுமைக்கு அதிகாரமளித்தல்',
    "footer_description": "மலேசிய மூதாட்டிகள் மற்றும் குறைந்த வருமான குடும்பங்களுக்கு முக்கியமான சேவைகளை எளிதாக அணுக வலுவூட்டுதல்.",
    "address": "கிட்டாகேர் மலேசியா",
    "email": "மின்னஞ்சல்",
    "phone": "தொலைபேசி",
    "rights_reserved": "அனைத்துப் பதிப்புரிமைகளும் பாதுகாக்கப்பட்டவை.",
    "benefit1": "மையப்படுத்தப்பட்ட மற்றும் எளிய அணுகல்",
    "benefit1_desc": "அனைத்து முக்கியமான சேவைகள் ஒரே இடத்தில். மேலும் செயலிகளை மாறிக்கொண்டு செல்ல வேண்டியதில்லை.",
    "benefit2": "நேரமும் பணமும் சேமிக்கிறது",
    "benefit2_desc": "மருத்துவ மையங்கள், நிதி உதவி விண்ணப்பங்கள் போன்றவை எளிதில் செயற்கொள்ளலாம்.",
    "benefit3": "டிஜிட்டல் திறன்களை எளிதாக கற்றுக்கொள்ளுங்கள்",
    "benefit3_desc": "ஸ்மார்ட்போன்கள் பயன்படுத்துவது, மோசடிகளை தவிர்ப்பது போன்றவற்றை எளிதாக கற்றுக்கொள்ளுங்கள்.",
    "get_directions": "வழிமுறைகள் பெறுங்கள்",
    "gov_services_intro": "அரசு வளங்கள், விண்ணப்பங்கள் மற்றும் அதிகாரப்பூர்வ ஆவணங்களை இங்கே பெறுங்கள்.",
    "available_now": "இப்போது கிடைக்கும்",
    "coming_soon": "விரைவில் வருகிறது",
    "services_offered": "வழங்கப்படும் சேவைகள்:",
    "access_service": "சேவையை அணுகவும்",
    "online_applications": "ஆன்லைன் விண்ணப்பங்கள்",
    "status_checking": "நிலைச் சரிபார்ப்பு",
    "document_downloads": "ஆவண பதிவிறக்கங்கள்",
    "info_portal": "தகவல் தளம்",
    "resources": "ஏன் கிட்டாகேர்?",
    "resources_desc": "உங்கள் நாளைய வாழ்க்கையை எளிதாக்க கிட்டாகேர் பல்வேறு முக்கிய சேவைகளை வழங்குகிறது.",
    "question3": "நான் அரசு சேவைகளை எப்படி அணுகலாம்?",
    "answer3": "அரசு சேவைகள் பிரிவை தேர்வு செய்து எளிதாக அணுகலாம்.",
    "question2": "கிட்டாகேர் இலவசமா?",
    "answer2": "ஆம், கிட்டாகேர் அனைத்து பயனர்களுக்கும் முற்றிலும் இலவசம்.",
    "question1": "கிட்டாகேர் என்றால் என்ன?",
    "answer1": "மலேசிய மூதாட்டிகள் மற்றும் குறைந்த வருமான குடும்பங்களுக்கு முக்கிய சேவைகளை எளிதாக வழங்கும் தளம்தான் கிட்டாகேர்.",
    "gov_services_desc": "அரசு வளங்களை அணுகவும்",
    "healthcare_title": "மருத்துவ வளங்கள்",
    "healthcare_intro": "மருத்துவ வசதிகளை கண்டறிந்து, மருத்துவத் தகவல்களை பெறுங்கள்.",
    "find_facility": "மையத்தை தேடு",
    "emergency": "அவசரம்",
    "appointment": "நியமனம் ஒதுக்குங்கள்",
    "medical_records": "மருத்துவ பதிவுகள்",
    "faq": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    "community_title": "சமூக மற்றும் சமூக ஆதரவு",
    "community_intro": "உங்கள் உள்ளூர் சமூகத்துடன் இணைந்து ஆதரவு சேவைகளை பெறுங்கள்.",
    "join_community": "சமூகத்தில் சேருங்கள்",
    "find_support": "ஆதரவை பெறுங்கள்",
    "volunteer": "தன்னார்வம்",
    "events": "சமூக நிகழ்வுகள்",
    "contacts": "சமூக பணியாளர்களின் தொடர்புகள்",
    "contacts_desc": "ஆதரவு மற்றும் உதவிக்காக சமூக பணியாளர்களை தொடர்புகொள்ளுங்கள்.",
    "support_desc": "ஆதரவு சேவைகள் அடைவு",
    "employment_title": "வேலை மற்றும் வருமான ஆதரவு",
    "employment_intro": "வேலை வாய்ப்புகள் மற்றும் தொழில் வளங்களைப் பெறுங்கள்.",
    "search_jobs": "வேலை தேடு",
    "career_resources": "தொழில் வளங்கள்",
    "training": "பயிற்சி திட்டங்கள்",
    "financial_aid": "நிதி உதவி",
    "peer_support": "சக பயனர் ஆதரவு & விவாதக் குழுக்கள்",
    "peer_desc": "அனுபவங்களை பகிரவும், கேள்விகளை கேட்கவும், உணர்வுப் பின்புல ஆதரவைப் பெறவும்.",
    "help": "உதவியை கேளுங்கள் & வழங்குங்கள்",
    "help_desc": "உதவியை கேட்கவும் அல்லது பிறருக்கு உதவுங்கள்.",
    "digital_title": "டிஜிட்டல் கல்வி",
    "digital_intro": "முக்கியமான டிஜிட்டல் திறன்களை கற்றுக்கொண்டு ஆன்லைனில் பாதுகாப்பாக இருங்கள்.",
    "basic_skills": "அடிப்படை திறன்கள்",
    "online_safety": "ஆன்லைன் பாதுகாப்பு",
    "digital_tools": "டிஜிட்டல் கருவிகள்",
    "practice_exercises": "பயிற்சி பயணிகள்",
    "AI": "AI கற்றல்",
    "AI_desc": "AI மற்றும் அதன் பயன்பாடுகள் பற்றி கற்றுக்கொள்ளுங்கள்",
    "Smartphone_usage": "ஸ்மார்ட்போன் பயன்பாடு",
    "smartphone_desc": "ஸ்மார்ட்போன்கள் மற்றும் செயலிகளை எவ்வாறு பயன்படுத்துவது என்பதை கற்றுக்கொள்ளுங்கள்",
    "online_services": "ஆன்லைன் சேவைகள்",
    "online_desc": "ஆன்லைன் சேவைகள் மற்றும் அவற்றை பயன்படுத்துவது பற்றி கற்றுக்கொள்ளுங்கள்",
    "online_payment": "ஆன்லைன் கட்டணம்",
    "payment_desc": "ஆன்லைன் கட்டணம் மற்றும் அதை எவ்வாறு பயன்படுத்துவது என்பதைக் கற்றுக்கொள்ளுங்கள்",
    "safety_desc": "ஆன்லைனில் பாதுகாப்பாக இருப்பது குறித்து கற்றுக்கொள்ளுங்கள்",
    "safety": "பாதுகாப்பு",
    "oku": "ஓ.கு.வர்களுக்கான அணுகல் கருவிகள்",
    "oku_desc": "ஓ.கு.வர்களுக்கான ஸ்க்ரீன் ரீடர்கள், குரல் கட்டளைகள், மற்றும் மொபைல் அமைப்புகளை பற்றி கற்றுக்கொள்ளுங்கள்.",
    "accessibility": "அணுகல்",
    "maps": "முகவரிகள் பயன்பாடு",
    "maps_desc": "இடங்களை தேடவும், வழிகளைப் பெறவும், நேரடி பயணத் தகவல்களைப் பயன்படுத்தவும் கற்றுக்கொள்ளுங்கள்.",
    "scam": "மோசடி விழிப்புணர்வு",
    "scam_desc": "மோசடிகளை அடையாளம் காண்பதும் தவிர்ப்பதும் எப்படி என்பதை கற்றுக்கொள்ளுங்கள்",
    "our_services": "எங்கள் சேவைகள்",
    "our_services_desc": "உங்கள் தினசரி வாழ்க்கையை எளிதாக்க எங்கள் பல்வேறு சேவைகள் உள்ளன.",
    "not_found": "பக்கம் காணப்படவில்லை",
    "not_found_message": "நீங்கள் தேடும் பக்கம் இல்லை.",
    "back_home": "முகப்புக்கு திரும்பவும்",
    "ai_learning": "AI கற்றல்",
    "ai_learning_desc": "தினசரி வாழ்க்கையில் AI மற்றும் அதன் பயன்பாடுகளை பற்றி கற்றுக்கொள்ளுங்கள்",
    "ai_intro_title": "AI அறிமுகம்",
    "ai_intro_content": "செயற்கை நுண்ணறிவு (AI) என்பது கணினிகள் மனிதர்களைப் போலவே கற்றுக்கொள்ள, யோசிக்க மற்றும் முடிவெடுக்கச் செய்யும் தொழில்நுட்பம். இது ஏற்கனவே நம்மைச் சுற்றியுள்ள ஸ்மார்ட்போன்கள், ஸ்மார்ட் ஹோம் சாதனங்கள், மற்றும் ஆன்லைன் சேவைகளில் உள்ளது.",
    "ai_basics_title": "AI அடிப்படைகள் புரிதல்",
    "ai_basics_content": "AI அமைப்புகள் பேச்சைக் கண்டறியவும், உரையை புரிந்துகொள்ளவும், கணிப்புகளைச் செய்யவும் முடியும். அவை எடுத்துக்காட்டுகளிலிருந்து கற்றுக்கொண்டு மேம்படுகின்றன.",
    "ai_applications_title": "தினசரி வாழ்க்கையில் AI",
    "ai_applications_content": "AI நினைவூட்டல்களை அமைக்க, தகவல்களை கண்டுபிடிக்க, அட்டவணைகளை நிர்வகிக்க உதவுகிறது. மொழிபெயர்ப்பு, படங்கள் அடையாளம் காண்பது மற்றும் மருத்துவ கண்காணிப்பிலும் உதவுகிறது.",
    "ai_ethics_title": "AI பாதுகாப்பு மற்றும் ஒழுக்கம்",
    "ai_ethics_content": "AI சக்திவாய்ந்ததாக இருந்தாலும், அதை பாதுகாப்பாகவும் ஒழுக்கத்தோடு பயன்படுத்துவது முக்கியம். தனியுரிமை கவலைகளைப் புரிந்து கொள்ளுங்கள்.",
    "ai_future_title": "AI இன் எதிர்காலம்",
    "ai_future_content": "AI தொழில்நுட்பம் தொடர்ந்து மேம்படுகிறது. புதிய சவால்கள் மற்றும் வாய்ப்புகளை இது கொண்டுவருகிறது. மனிதத் தீர்மானங்களை மாற்றாமல், உதவியாக AI யைப் பயன்படுத்துங்கள்.",
    "step": "படி",
    "next": "அடுத்தது",
    "finish": "முடிக்கவும்",
    "completed": "முடிக்கப்பட்டது",

    // Careers page translations
    careers: 'தொழில்கள்',
    careers_intro: 'சுவாரஸ்யமான தொழில் வாய்ப்புகளை ஆராயுங்கள் மற்றும் உங்கள் அடுத்த தொழில்முறை பயணத்தைக் கண்டறியுங்கள்.',
    requirements: 'தேவைகள்',
    salary_range: 'சம்பள வரம்பு',
    location: 'இடம்',
    apply_now: 'இப்போது விண்ணப்பிக்கவும்',
    hot_job: 'அதிக தேவை',
    company: 'நிறுவனம்',
    job_type: 'வேலை வகை',
    experience_level: 'அனுபவ நிலை',
    full_time: 'முழு நேரம்',
    part_time: 'பகுதி நேரம்',
    contract: 'ஒப்பந்தம்',
    entry_level: 'தொடக்க நிலை',
    mid_level: 'இடைநிலை',
    Any : 'எந்த',
    find : 'கண்டுபிடி',
    senior: 'மூத்த',
    application_success: 'விண்ணப்பம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
    application_error: 'விண்ணப்பத்தைச் சமர்ப்பிக்க முடியவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    retry: 'மீண்டும் முயற்சிக்கவும்',
    quick_links: 'விரைவு இணைப்புகள்',
    
    // Community Support page translations
    community_support: 'சமூக ஆதரவு',
    community_support_intro: 'நீங்கள் செழிக்க உதவும் சமூக வளங்கள் மற்றும் ஆதரவு சேவைகளை அணுகவும்.',
    senior_citizen_support: 'மூத்த குடிமக்கள் ஆதரவு',
    senior_citizen_support_desc: 'சுகாதாரம், சமூக நடவடிக்கைகள் மற்றும் உதவித் திட்டங்கள் உள்ளிட்ட மூத்த குடிமக்களுக்கான விரிவான ஆதரவு சேவைகள்.',
    community_centers: 'சமூக மையங்கள்',
    community_centers_desc: 'அனைத்து வயதினருக்கும் பல்வேறு நிகழ்ச்சிகள் மற்றும் செயல்பாடுகளை வழங்கும் உள்ளூர் சமூக மையங்கள்.',
    volunteer_programs: 'தன்னார்வ திட்டங்கள்',
    volunteer_programs_desc: 'எங்கள் தன்னார்வத் திட்டங்களில் சேர்ந்து உங்கள் சமூகத்தில் மாற்றத்தை ஏற்படுத்துங்கள்.',
    emergency_support: 'அவசர ஆதரவு',
    emergency_support_desc: 'உடனடி உதவி மற்றும் நெருக்கடி தலையீட்டிற்கான 24/7 அவசர ஆதரவு சேவைகள்.',
    family_support: 'குடும்ப ஆதரவு',
    family_support_desc: 'பெற்றோர் வளங்கள் மற்றும் குடும்ப நடவடிக்கைகள் உள்ளிட்ட விரிவான குடும்ப ஆதரவு சேவைகள்.',
    mental_health: 'மன நல சேவைகள்',
    mental_health_desc: 'தொழில்முறை மன நல ஆதரவு மற்றும் நலவாழ்வு திட்டங்கள்.',
    connect: 'இணைக்க',
    services_offered: 'வழங்கப்படும் சேவைகள்'
  },
};  

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    const saved = localStorage.getItem('kitacare-language');
    return saved || 'en';
  });

  const changeLanguage = (langCode) => {
    setCurrentLanguage(langCode);
    localStorage.setItem('kitacare-language', langCode);
  };

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key];
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, languages, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);